spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: is-cw-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${database_url:jdbc:postgresql://localhost:5432/fitness}
    username: ${database_username:root}
    password: ${database_password:root}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false


jwt:
  secret: ${jwt_secret:7dec524d50d2b1ec883f422e015659b1e57e42305e84c3cabb6d70911de2bc24}



server:
  port: ${server_port:8083}